// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/midtrans/midtrans-go/coreapi"
	"gorm.io/gorm"
	"ragamaya-api/midtrans/notifications/controllers"
	"ragamaya-api/midtrans/notifications/services"
)

// Injectors from injector.go:

func InitializeNotificationController(db *gorm.DB, validate *validator.Validate, midtransCore *coreapi.Client) controllers.CompControllers {
	compServices := services.NewComponentServices(db, validate)
	compControllers := controllers.NewCompController(compServices)
	return compControllers
}

// injector.go:

var notificationFeatureSet = wire.NewSet(services.NewComponentServices, controllers.NewCompController)
