package exceptions

const (
	ErrInvalidCredentials              = "invalid credentials"
	ErrUnauthorized                    = "unauthorized access"
	ErrBadRequest                      = "invalid request body or parameters"
	ErrForbidden                       = "forbidden access"
	ErrNotSeller                       = "you are not a seller"
	ErrNotFound                        = "record not found"
	ErrInternalServer                  = "something went wrong"
	ErrEmailNotVerified                = "email not verified"
	ErrEmailSendFailed                 = "failed to send email"
	ErrEmailAlreadyRegistered          = "email already registered"
	ErrDatabaseCommunication           = "failed to communicate with database"
	ErrTokenGenerate                   = "failed to generate token"
	ErrCredentialsHash                 = "failed to secure credentials"
	ErrFileUpload                      = "failed to upload file"
	ErrFilePermission                  = "failed to set file permission"
	ErrFileSize                        = "file size exceeds the limit"
	ErrJsonMarshal                     = "failed to marshal JSON"
	ErrFileRead                        = "failed to read file"
	ErrFileURL                         = "invalid file URL"
	ErrRegisteredWithGoogle            = "user already registered with Google"
	ErrRegisteredWithCredentials       = "user already registered with credentials"
	ErrNotCheckedInYet                 = "reservation not checked in yet"
	ErrNotCheckedOutYet                = "reservation not checked out yet"
	ErrInvalidDate                     = "invalid date"
	ErrInvalidTokenStructure           = "invalid token structure"
	ErrDataNotVerified                 = "data not verified"
	ErrNotTheOwner                     = "you are not the owner of this resource"
	ErrCheckoutQuantityMoreThanStocks  = "checkout quantity more than stocks"
	ErrCheckoutQuantityMoreThanAllowed = "checkout quantity more than allowed"
	ErrAlreadyOwned                    = "you already own this product"
)
