// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"gorm.io/gorm"
	controllers4 "ragamaya-api/api/products/controllers"
	repositories4 "ragamaya-api/api/products/repositories"
	services4 "ragamaya-api/api/products/services"
	controllers3 "ragamaya-api/api/sellers/controllers"
	repositories3 "ragamaya-api/api/sellers/repositories"
	services3 "ragamaya-api/api/sellers/services"
	controllers2 "ragamaya-api/api/storages/controllers"
	repositories2 "ragamaya-api/api/storages/repositories"
	services2 "ragamaya-api/api/storages/services"
	"ragamaya-api/api/users/controllers"
	"ragamaya-api/api/users/repositories"
	"ragamaya-api/api/users/services"
)

// Injectors from injector.go:

func InitializeUserController(db *gorm.DB, validate *validator.Validate) controllers.CompControllers {
	compRepositories := repositories.NewComponentRepository()
	compServices := services.NewComponentServices(compRepositories, db, validate)
	compControllers := controllers.NewCompController(compServices)
	return compControllers
}

func InitializeStorageController(db *gorm.DB, s3client *s3.Client, validate *validator.Validate) controllers2.CompControllers {
	compRepositories := repositories2.NewComponentRepository()
	compServices := services2.NewComponentServices(compRepositories, db, s3client, validate)
	compControllers := controllers2.NewCompController(compServices)
	return compControllers
}

func InitializeSellerController(db *gorm.DB, validate *validator.Validate) controllers3.CompControllers {
	compRepositories := repositories3.NewComponentRepository()
	repositoriesCompRepositories := repositories.NewComponentRepository()
	compServices := services3.NewComponentServices(compRepositories, db, validate, repositoriesCompRepositories)
	compControllers := controllers3.NewCompController(compServices)
	return compControllers
}

func InitializeProductController(db *gorm.DB, validate *validator.Validate) controllers4.CompControllers {
	compRepositories := repositories4.NewComponentRepository()
	compServices := services4.NewComponentServices(compRepositories, db, validate)
	compControllers := controllers4.NewCompController(compServices)
	return compControllers
}

// injector.go:

var userFeatureSet = wire.NewSet(repositories.NewComponentRepository, services.NewComponentServices, controllers.NewCompController)

var storageFeatureSet = wire.NewSet(repositories2.NewComponentRepository, services2.NewComponentServices, controllers2.NewCompController)

var sellerFeatureSet = wire.NewSet(repositories3.NewComponentRepository, services3.NewComponentServices, controllers3.NewCompController, repositories.NewComponentRepository)

var productFeatureSet = wire.NewSet(repositories4.NewComponentRepository, services4.NewComponentServices, controllers4.NewCompController)
